# Generated by Django 5.2.1 on 2025-05-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corridas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='data',
            field=models.DateTimeField(default='2025-05-22'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corrida',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
